import type { Cycle, FundState, Agent } from "./types";

export const MOCK_FUND: FundState = {
  nav: 1247.83,
  navChange24h: 4.2,
  totalCycles: 48,
  totalPayments: 384,
  totalSpend: 0.58,
  winRate: 76,
  totalInferences: 288,
  positions: [{ asset: "ETH", percentage: 12 }],
  userShares: 1200,
  userDeposited: 1200,
  userValue: 1247.83,
};

export const MOCK_CYCLE: Cycle = {
  id: 48,
  timestamp: "2026-04-04T14:32:17Z",
  specialists: [
    {
      name: "SentimentBot",
      emoji: "🧠",
      analysis: "Crypto Twitter 72% bullish. Fear & Greed: 68. Sentiment shift +12% in 4h.",
      price: 0.001,
      attestation: "0xa7c3e91f...d42b",
      model: "glm-5-chat",
      provider: "0x9f2b...4a1c",
      inftId: "#0847",
    },
    {
      name: "WhaleEye",
      emoji: "🐋",
      analysis: "12,400 ETH accumulated by whales in 24h. Exchange outflows +8%.",
      price: 0.001,
      attestation: "0xb8d4f02a...e73c",
      model: "glm-5-chat",
      provider: "0x9f2b...4a1c",
      inftId: "#0848",
    },
    {
      name: "MomentumX",
      emoji: "📈",
      analysis: "RSI: 42 recovering. MACD bullish crossover on 4h. Volume +23%.",
      price: 0.001,
      attestation: "0xc9e5a13b...f84d",
      model: "glm-5-chat",
      provider: "0x9f2b...4a1c",
      inftId: "#0849",
    },
  ],
  adversarial: {
    alpha: {
      argument:
        "All 3 specialists bullish. Whale accumulation + RSI recovery + positive sentiment convergence.",
      recommendation: "BUY 20% ETH",
      attestation: "0xd0f6b24c...a95e",
    },
    risk: {
      argument:
        "Funding rates elevated at 0.04%. Open interest at 30-day high. Last similar pattern led to 11% drawdown.",
      recommendation: "HOLD. Max 10%",
      attestation: "0xe1a7c35d...b06f",
    },
    executor: {
      argument:
        "Alpha's whale signal compelling. Risk's funding concern valid. Compromise position with tight stop.",
      recommendation: "BUY 12% ETH. Stop -4%",
      attestation: "0xf2b8d46e...c17a",
    },
  },
  payments: [
    { from: "Main", to: "SentimentBot", amount: 0.001, txHash: "0x1a2b...", chain: "arc" },
    { from: "Main", to: "WhaleEye", amount: 0.001, txHash: "0x3c4d...", chain: "arc" },
    { from: "Main", to: "MomentumX", amount: 0.001, txHash: "0x5e6f...", chain: "arc" },
  ],
  hcs: { topicId: "0.0.5847291", sequenceNumber: 48, timestamp: "14:32:17Z" },
  trade: { action: "BUY", asset: "ETH", percentage: 12, stopLoss: -4 },
  memory: [
    {
      cycleRef: 41,
      text: "When RSI was 42 and sentiment was 70%+ bullish, buying 10-15% yielded +4.2% avg over next 3 cycles",
    },
    {
      cycleRef: 33,
      text: "Funding rates above 0.03% preceded a drawdown 7 out of 9 times — Risk agent was correct to limit exposure",
    },
    {
      cycleRef: 28,
      text: "Whale accumulation above 10K ETH/day was followed by 6%+ upside within 48h in 4 of 5 instances",
    },
  ],
};

export const MOCK_HISTORY: Array<
  Cycle & { pnl: number; win: boolean }
> = [
  {
    ...MOCK_CYCLE,
    id: 48,
    timestamp: "2026-04-04T14:32:00Z",
    pnl: 6.14,
    win: true,
    trade: { action: "BUY", asset: "ETH", percentage: 12, stopLoss: -4 },
    adversarial: {
      alpha: { argument: "Whale accumulation + bullish RSI convergence.", recommendation: "Buy 20%", attestation: "" },
      risk: { argument: "Max 10% — funding rates 0.04%", recommendation: "Max 10%", attestation: "" },
      executor: { argument: "Compromise 12%, stop-loss -4%", recommendation: "BUY 12% ETH", attestation: "" },
    },
  },
  {
    ...MOCK_CYCLE,
    id: 47,
    timestamp: "2026-04-04T14:27:00Z",
    pnl: 0,
    win: true,
    trade: { action: "HOLD", asset: "ETH", percentage: 0, stopLoss: null },
    adversarial: {
      alpha: { argument: "Slight bullish divergence.", recommendation: "Hold", attestation: "" },
      risk: { argument: "Volume too low to confirm.", recommendation: "Hold", attestation: "" },
      executor: { argument: "Hold — insufficient confluence.", recommendation: "HOLD", attestation: "" },
    },
  },
  {
    ...MOCK_CYCLE,
    id: 46,
    timestamp: "2026-04-04T14:22:00Z",
    pnl: -1.23,
    win: false,
    trade: { action: "SELL", asset: "ETH", percentage: 5, stopLoss: null },
    adversarial: {
      alpha: { argument: "Momentum fading.", recommendation: "Reduce 5%", attestation: "" },
      risk: { argument: "Agree — rising exchange inflows.", recommendation: "Sell 5%", attestation: "" },
      executor: { argument: "Reduce 5%, take partial profit.", recommendation: "SELL 5% ETH", attestation: "" },
    },
  },
  {
    ...MOCK_CYCLE,
    id: 45,
    timestamp: "2026-04-04T14:17:00Z",
    pnl: 3.87,
    win: true,
    trade: { action: "BUY", asset: "ETH", percentage: 8, stopLoss: -3 },
    adversarial: {
      alpha: { argument: "Oversold bounce incoming.", recommendation: "Buy 8%", attestation: "" },
      risk: { argument: "Only 8% — macro uncertainty.", recommendation: "Max 8%", attestation: "" },
      executor: { argument: "Buy 8%, tight stop -3%.", recommendation: "BUY 8% ETH", attestation: "" },
    },
  },
  {
    ...MOCK_CYCLE,
    id: 44,
    timestamp: "2026-04-04T14:12:00Z",
    pnl: 0,
    win: true,
    trade: { action: "HOLD", asset: "ETH", percentage: 0, stopLoss: null },
    adversarial: {
      alpha: { argument: "No clear signal.", recommendation: "Hold", attestation: "" },
      risk: { argument: "Agree.", recommendation: "Hold", attestation: "" },
      executor: { argument: "Hold.", recommendation: "HOLD", attestation: "" },
    },
  },
  {
    ...MOCK_CYCLE,
    id: 43,
    timestamp: "2026-04-04T14:07:00Z",
    pnl: 9.41,
    win: true,
    trade: { action: "BUY", asset: "ETH", percentage: 15, stopLoss: -5 },
    adversarial: {
      alpha: { argument: "Massive whale buy + sentiment flip.", recommendation: "Buy 15%", attestation: "" },
      risk: { argument: "Elevated OI but signal strong.", recommendation: "Max 15%", attestation: "" },
      executor: { argument: "Buy 15%, wider stop -5%.", recommendation: "BUY 15% ETH", attestation: "" },
    },
  },
];

export const MOCK_AGENTS: Agent[] = [
  {
    name: "SentimentBot",
    emoji: "🧠",
    skill: "Twitter + Reddit sentiment",
    accuracy: 78,
    timesHired: 312,
    pricePerQuery: 0.001,
    inftId: "#0847",
    model: "glm-5-chat",
    provider: "0x9f2b...4a1c",
    creator: "VaultMind",
    isActive: true,
  },
  {
    name: "WhaleEye",
    emoji: "🐋",
    skill: "Whale wallet movements",
    accuracy: 82,
    timesHired: 445,
    pricePerQuery: 0.001,
    inftId: "#0848",
    model: "glm-5-chat",
    provider: "0x9f2b...4a1c",
    creator: "VaultMind",
    isActive: true,
  },
  {
    name: "MomentumX",
    emoji: "📈",
    skill: "RSI, MACD, volume analysis",
    accuracy: 74,
    timesHired: 289,
    pricePerQuery: 0.001,
    inftId: "#0849",
    model: "glm-5-chat",
    provider: "0x9f2b...4a1c",
    creator: "VaultMind",
    isActive: true,
  },
  {
    name: "FundingRadar",
    emoji: "📡",
    skill: "Perp funding rates",
    accuracy: 71,
    timesHired: 134,
    pricePerQuery: 0.002,
    inftId: "#1201",
    model: "glm-5-chat",
    provider: "0x4b2c...9e3f",
    creator: "0x7a3f...8b2c",
    isActive: false,
  },
  {
    name: "YieldHunter",
    emoji: "🌾",
    skill: "DeFi yield comparison",
    accuracy: 69,
    timesHired: 87,
    pricePerQuery: 0.003,
    inftId: "#1202",
    model: "glm-5-chat",
    provider: "0x4b2c...9e3f",
    creator: "0x4b2c...7a1d",
    isActive: false,
  },
  {
    name: "NewsFlash",
    emoji: "⚡",
    skill: "Breaking crypto news",
    accuracy: 66,
    timesHired: 201,
    pricePerQuery: 0.001,
    inftId: "#1203",
    model: "glm-5-chat",
    provider: "0x4b2c...9e3f",
    creator: "0x9d1e...3c5f",
    isActive: false,
  },
  {
    name: "MEVGuard",
    emoji: "🛡️",
    skill: "Sandwich attack detection",
    accuracy: 88,
    timesHired: 56,
    pricePerQuery: 0.005,
    inftId: "#1204",
    model: "glm-5-chat",
    provider: "0x4b2c...9e3f",
    creator: "0x2f8a...6d4e",
    isActive: false,
  },
];

export const MOCK_TRANSACTIONS = [
  { type: "Deposit", amount: 500, timeAgo: "2h ago", hash: "0x7f3a..." },
  { type: "Deposit", amount: 200, timeAgo: "1d ago", hash: "0x4b2c..." },
  { type: "Deposit", amount: 500, timeAgo: "3d ago", hash: "0x9d1e..." },
];
